language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'

env:
  matrix:
   - DB=MYSQL CORE_RELEASE=3.0
   - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=master

before_script:
 - phpenv rehash
 - composer self-update
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - vendor/bin/phpunit modulator/tests/
